import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LoveFooter from "@/components/LoveFooter";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`scroll-smooth`} lang="en">
      <body
        className={`${manrope.className} flex flex-col items-center justify-center  scroll-smooth`}
      >
        <Navbar />
        {children}
        <Footer />
        <LoveFooter />
      </body>
    </html>
  );
}
